### ISSUE TITLE
How do I run it, doesn't find keyboard module

### ISSUE THREAD

**Issue by SlitIRL** [AbsoluteWinter/more-ore-combo-autoclick#3]
Hi, I know this is an old project but I still have to ask... How do I run this?

It keeps saying ModuleNotFoundError: No module named 'keyboard'

Sorry for the trouble.

**Comment by SlitIRL** [comment]
PS: I installed all of the requirements, I made sure that keyboard exists on the system Requirement already satisfied: keyboard in c:\path

**Comment by AbsoluteWinter** [comment]
Hi SlitlRL,

Thank you for your attention to this project. You can try reinstalling the keyboard module from the official website: https://pypi.org/project/keyboard/

If it still doesn't work, you might want to check if you have multiple Python versions installed, and ensure that you installed the module for the correct version.
